[2024-08-01T18:39:56.728+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-01T18:39:56.740+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nyc_taxi_etl_continuous.process_month scheduled__2023-01-03T00:00:00+00:00 [queued]>
[2024-08-01T18:39:56.748+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nyc_taxi_etl_continuous.process_month scheduled__2023-01-03T00:00:00+00:00 [queued]>
[2024-08-01T18:39:56.748+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-08-01T18:39:56.762+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): process_month> on 2023-01-03 00:00:00+00:00
[2024-08-01T18:39:56.770+0000] {standard_task_runner.py:57} INFO - Started process 1962 to run task
[2024-08-01T18:39:56.773+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'nyc_taxi_etl_continuous', 'process_month', 'scheduled__2023-01-03T00:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/nyc_taxi_etl.py', '--cfg-path', '/tmp/tmppd628gx9']
[2024-08-01T18:39:56.778+0000] {standard_task_runner.py:85} INFO - Job 32: Subtask process_month
[2024-08-01T18:39:56.822+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-01T18:39:56.894+0000] {task_command.py:410} INFO - Running <TaskInstance: nyc_taxi_etl_continuous.process_month scheduled__2023-01-03T00:00:00+00:00 [running]> on host 6d66194ad4f7
[2024-08-01T18:39:56.913+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-01T18:39:59.480+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nyc_taxi_etl_continuous' AIRFLOW_CTX_TASK_ID='process_month' AIRFLOW_CTX_EXECUTION_DATE='2023-01-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-03T00:00:00+00:00'
[2024-08-01T18:39:59.505+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:313 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-08-01T18:41:01.699+0000] {transform_data.py:10} INFO - Processing data for 2023-01
[2024-08-01T18:41:01.707+0000] {transform_data.py:11} INFO - Columns in the dataset: ['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime', 'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag', 'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge', 'total_amount', 'congestion_surcharge', 'airport_fee']
[2024-08-01T18:41:04.137+0000] {transform_data.py:47} ERROR - Error processing data for 2023-01: 'RateCodeID'
[2024-08-01T18:41:04.142+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'RateCodeID'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/nyc_taxi_etl.py", line 31, in process_month
    clean_and_transform_data(year, month)
  File "/opt/airflow/scripts/transform_data.py", line 32, in clean_and_transform_data
    (df['payment_type'].isin(range(1, 7))) &
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'RateCodeID'
[2024-08-01T18:41:04.240+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=nyc_taxi_etl_continuous, task_id=process_month, execution_date=20230103T000000, start_date=20240801T183956, end_date=20240801T184104
[2024-08-01T18:41:04.295+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 32 for task process_month ('RateCodeID'; 1962)
[2024-08-01T18:41:04.468+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-08-01T18:41:04.560+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-01T19:00:38.243+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-01T19:00:38.255+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nyc_taxi_etl_continuous.process_month scheduled__2023-01-03T00:00:00+00:00 [queued]>
[2024-08-01T19:00:38.265+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nyc_taxi_etl_continuous.process_month scheduled__2023-01-03T00:00:00+00:00 [queued]>
[2024-08-01T19:00:38.265+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-08-01T19:00:38.290+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): process_month> on 2023-01-03 00:00:00+00:00
[2024-08-01T19:00:38.302+0000] {standard_task_runner.py:57} INFO - Started process 2365 to run task
[2024-08-01T19:00:38.313+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'nyc_taxi_etl_continuous', 'process_month', 'scheduled__2023-01-03T00:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/nyc_taxi_etl.py', '--cfg-path', '/tmp/tmp35z1zpam']
[2024-08-01T19:00:38.317+0000] {standard_task_runner.py:85} INFO - Job 34: Subtask process_month
[2024-08-01T19:00:38.358+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-01T19:00:38.443+0000] {task_command.py:410} INFO - Running <TaskInstance: nyc_taxi_etl_continuous.process_month scheduled__2023-01-03T00:00:00+00:00 [running]> on host 6d66194ad4f7
[2024-08-01T19:00:38.476+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-01T19:00:39.528+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nyc_taxi_etl_continuous' AIRFLOW_CTX_TASK_ID='process_month' AIRFLOW_CTX_EXECUTION_DATE='2023-01-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-03T00:00:00+00:00'
[2024-08-01T19:00:39.530+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:313 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-08-01T19:01:46.893+0000] {transform_data.py:10} INFO - Processing data for 2023-01
[2024-08-01T19:01:46.909+0000] {transform_data.py:11} INFO - Columns in the dataset: ['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime', 'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag', 'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge', 'total_amount', 'congestion_surcharge', 'airport_fee']
[2024-08-01T19:02:08.841+0000] {transform_data.py:44} INFO - Cleaned data saved to data/cleaned_yellow_tripdata_2023_01.parquet
[2024-08-01T19:03:37.538+0000] {logging_mixin.py:149} INFO - Loaded cleaned data for 2023-01 to BigQuery
[2024-08-01T19:03:37.548+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-08-01T19:03:37.659+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=nyc_taxi_etl_continuous, task_id=process_month, execution_date=20230103T000000, start_date=20240801T190038, end_date=20240801T190337
[2024-08-01T19:03:37.893+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-08-01T19:03:38.032+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
