[2024-08-01T14:31:58.792+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nyc_taxi_etl.upload_to_gcs manual__2024-08-01T14:30:46.358137+00:00 [queued]>
[2024-08-01T14:31:58.838+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nyc_taxi_etl.upload_to_gcs manual__2024-08-01T14:30:46.358137+00:00 [queued]>
[2024-08-01T14:31:58.839+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-08-01T14:31:58.865+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): upload_to_gcs> on 2024-08-01 14:30:46.358137+00:00
[2024-08-01T14:31:58.878+0000] {standard_task_runner.py:57} INFO - Started process 221 to run task
[2024-08-01T14:31:58.883+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'nyc_taxi_etl', 'upload_to_gcs', 'manual__2024-08-01T14:30:46.358137+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/nyc_taxi_etl.py', '--cfg-path', '/tmp/tmpfqchf37w']
[2024-08-01T14:31:58.885+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask upload_to_gcs
[2024-08-01T14:31:58.903+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-01T14:31:58.954+0000] {task_command.py:410} INFO - Running <TaskInstance: nyc_taxi_etl.upload_to_gcs manual__2024-08-01T14:30:46.358137+00:00 [running]> on host 31f8257a797f
[2024-08-01T14:31:59.309+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nyc_taxi_etl' AIRFLOW_CTX_TASK_ID='upload_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2024-08-01T14:30:46.358137+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-01T14:30:46.358137+00:00'
[2024-08-01T14:31:59.310+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: upload_to_gcs() missing 1 required positional argument: 'credentials'
[2024-08-01T14:31:59.318+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=nyc_taxi_etl, task_id=upload_to_gcs, execution_date=20240801T143046, start_date=20240801T143158, end_date=20240801T143159
[2024-08-01T14:31:59.330+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 6 for task upload_to_gcs (upload_to_gcs() missing 1 required positional argument: 'credentials'; 221)
[2024-08-01T14:31:59.366+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-08-01T14:31:59.395+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
